import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]/'content'
def action(id,label,explanation,source=16,**kw):
 return dict(id=id,label=label,explanation=explanation,source=f'Ситуации на борту, №{source}',**kw)
def node(text,*actions): return dict(text=text,actions=actions)
def check(label,c,default=False): return dict(label=label,competency=c,default=default)
comm='Общение'; proc='Порядок действий'; safe='Безопасность'
s=dict(id='service',version='1',title='Сервис и свободный проход',intro='Пассажир не может зарядить ноутбук. Пока вы разговариваете, в проходе появляется чемодан. Разберитесь с обоими обращениями.',seconds=45,critical_timeout=False,initial={'service':'a0'},rubric={
 'apology':check('Признать неудобство и извиниться',comm),'promise':check('Не обещать неподтверждённый ремонт',comm,True),'polite':check('Вежливо попросить убрать багаж',comm),
 'seat':check('Проверить место того же класса',proc),'report':check('Сообщить начальнику поезда и инженеру',proc),'return':check('Вернуться с подтверждённой информацией',proc),
 'owner':check('Установить владельца багажа',safe),'location':check('Предложить конкретное место для багажа',safe),'timely':check('Освободить проход до учебного срока',safe)},nodes={})
n=s['nodes']
n['a0']=node('«Розетка не работает. Мне нужно зарядить ноутбук — впереди важная встреча».',
 action('apologize','Прошу прощения за неудобство. Проверю, что можно предложить.','Вы признали неудобство, извинились и не дали неподтверждённых обещаний.',loyalty=5,checks={'apology':True},next='a1',open='b0'),
 action('promise','Сейчас обязательно всё починят.','Срок ремонта не подтверждён. Лучше извиниться и проверить доступное решение.',loyalty=3,flags={'promise':True},checks={'promise':False},next='a1',open='b0'),
 action('dismiss','Это не моя проблема.','Пассажиру нужна помощь. Следует выслушать его, извиниться и сообщить ответственным.',loyalty=-10,next='a1',open='b0'))
report=action('report','Сообщить начальнику поезда и инженеру.','Неисправность передана обоим ответственным сотрудникам.',flags={'reported':True},checks={'report':True},when={'reported':False})
exit=action('leave','Прекратить разговор.','Вопрос пассажира остался нерешённым. Обращение закрыто без решения.',loyalty=-10,next='closed_unresolved')
n['a1']=node('Уточните, есть ли разрешённое свободное место в том же классе обслуживания.',action('check','Проверить доступные места того же класса.','Вы проверили допустимую альтернативу, прежде чем предлагать пересадку.',checks={'seat':True},next='a2'),report,exit)
n['a2']=node('Проверка мест выполнена. Предложите пассажиру подтверждённое решение.',action('offer','Предложить свободное место того же класса.','Место проверено и доступно: пересадка решает проблему пассажира.',when={'seat':True},loyalty=10,next='a3'),action('none','Объяснить, что свободных мест сейчас нет.','Отсутствие свободного места не является вашей ошибкой. Сообщите о неисправности и вернитесь с подтверждённой информацией.',when={'seat':False},loyalty=5,next='a3'),exit)
n['a3']=node('Передайте информацию ответственным и вернитесь к пассажиру.',report,action('return','Вернуться к пассажиру с подтверждённой информацией.','Пассажир знает, что сообщение принято. Вы не обещаете неподтверждённых сроков ремонта.',when={'reported':True},checks={'return':True},loyalty=5,next='closed_resolved'),exit)
n['b0']=node('Чемодан перекрывает проход. Рядом находятся пассажиры.',action('owner','Спросить, кому принадлежит чемодан.','Владелец отозвался. Можно попросить его переместить багаж.',14,checks={'owner':True},flags={'owner':True},next='b1'),action('later','Отложить обращение к владельцу.','Проход остаётся занят. Таймер продолжает идти.',14,loyalty=-3,when={'delayed':False},flags={'delayed':True}))
n['b1']=node('Владелец чемодана найден. Как попросить его освободить проход?',action('polite','Пожалуйста, уберите чемодан на багажную полку: проход должен быть свободен.','Владелец убрал чемодан в указанное место. Вы объяснили причину и сохранили вежливый тон.',14,loyalty=10,safety=20,checks={'polite':True,'location':True},next='closed_resolved',close_timer=True),action('rude','Немедленно уберите свой чемодан на полку!','Проход освобождён, но резкий тон ухудшил взаимодействие. Лучше спокойно объяснить причину.',14,loyalty=-15,safety=20,checks={'location':True},next='closed_resolved',close_timer=True),action('vague','Уберите куда-нибудь чемодан.','Вы не указали подходящее место. Проход пока не освобождён.',14,flags={'vague':True},when={'vague':False}))
t=dict(id='security',version='1',title='Похожая вещь — другое решение',intro='Обнаружен багаж без владельца. На обращение никто не откликнулся. Действуйте с учётом этого обстоятельства.',seconds=35,critical_timeout=True,initial={'security':'s0'},rubric={'touch':check('Не перемещать вещь',safe,True),'chief':check('Сообщить начальнику поезда',proc),'security':check('Сообщить работникам транспортной безопасности',proc),'warn':check('Предупредить пассажиров',comm)},nodes={})
warn=action('warn','Не трогать вещь и предупредить пассажиров.','Не перемещайте бесхозную вещь. Предупредите находящихся рядом пассажиров.',41,loyalty=5,safety=10,checks={'warn':True},flags={'warned':True},when={'warned':False})
notify=action('notify','По связи сообщить начальнику поезда и транспортной безопасности.','Информация передана ответственным. Дальнейшие действия выполняются по установленному алгоритму; полного алгоритма в датасете нет.',41,safety=10,checks={'chief':True,'security':True},flags={'notified':True},close_timer=True,when={'notified':False})
move=action('move','Перенести вещь, чтобы освободить проход.','Для бесхозной вещи это неверное решение. Нельзя переносить правило для багажа с известным владельцем на другую ситуацию.',41,safety=-60,checks={'touch':False},critical=True)
t['nodes']['s0']=node('Багаж без владельца: никто из пассажиров не подтвердил, что это его вещь.',warn,notify,move,action('wait','Отложить сообщение.','Промедление оставляет ситуацию без реакции ответственных сотрудников.',41,loyalty=-5,flags={'delayed':True},when={'delayed':False}),action('complete','Завершить обращение.','Вы предупредили пассажиров и передали сообщение ответственным. Следуйте установленному алгоритму.',41,when={'warned':True,'notified':True},next='closed_resolved'))
for item in (s,t): (root/(item['id']+'.json')).write_text(json.dumps(item,ensure_ascii=False,indent=2),encoding='utf8')
